name: bemyvoice
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^1.0.8
  video_player: ^2.8.5
  flutter_bloc: ^8.1.6
  flashy_tab_bar2: ^0.0.10
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  get_it: ^7.6.7
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  flutter_dotenv: ^5.1.0
  file_picker: ^8.0.0+1
  agora_uikit: ^1.3.10
  web_socket_channel: ^2.4.0
  firebase_database: ^10.4.9
  audioplayers: ^5.2.1
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.0
  avatar_glow: ^3.0.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - lib/config/.env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
