// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9qfrvKBz7-BtQf2vjyxRd_RaqCJ1iebI',
    appId: '1:753991794709:web:0b95d5d161e6505ca44e1c',
    messagingSenderId: '753991794709',
    projectId: 'be-my-voice-43875',
    authDomain: 'be-my-voice-43875.firebaseapp.com',
    databaseURL: 'https://be-my-voice-43875-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'be-my-voice-43875.appspot.com',
    measurementId: 'G-PV132Y5W6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk1yfvi7G4Ia5clQE5zmo4QqgGoGr4G8I',
    appId: '1:753991794709:android:581c4acaf26d101fa44e1c',
    messagingSenderId: '753991794709',
    projectId: 'be-my-voice-43875',
    databaseURL: 'https://be-my-voice-43875-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'be-my-voice-43875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBqWeM9s5XzTe6uUhlb-cV4pBsInGuw0',
    appId: '1:753991794709:ios:91d83d7655c76862a44e1c',
    messagingSenderId: '753991794709',
    projectId: 'be-my-voice-43875',
    databaseURL: 'https://be-my-voice-43875-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'be-my-voice-43875.appspot.com',
    androidClientId: '753991794709-pv572viimlesvejn4dcdd10tieu7pi01.apps.googleusercontent.com',
    iosClientId: '753991794709-e9grmb250eeurtfue25vt3hpakghihbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bemyvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9qfrvKBz7-BtQf2vjyxRd_RaqCJ1iebI',
    appId: '1:753991794709:web:a40fa2774a7d01eda44e1c',
    messagingSenderId: '753991794709',
    projectId: 'be-my-voice-43875',
    authDomain: 'be-my-voice-43875.firebaseapp.com',
    databaseURL: 'https://be-my-voice-43875-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'be-my-voice-43875.appspot.com',
    measurementId: 'G-B0WF9K2C8G',
  );

}